# Generated by Django 4.1.5 on 2023-12-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customers",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("FirstName", models.CharField(max_length=100)),
                ("LastName", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=100)),
                ("Price", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("Rating", models.CharField(max_length=100)),
                ("Review", models.CharField(max_length=100)),
                (
                    "CustomerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="new.customers"
                    ),
                ),
                (
                    "ProductsID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="new.products"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("Quantity", models.CharField(max_length=100)),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
                (
                    "CustomerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="new.customers"
                    ),
                ),
                (
                    "ProductsID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="new.products"
                    ),
                ),
            ],
        ),
    ]
